- templates/static_analysis.html
Certificate info contains lots of text that is better inside a pre tag. 
difference in output will be in terms of spacing and proper alignment.
> added <pre> tag for certificate info

- StaticAnalyzer/views.py
* Code Breaks on Windows systems if path contains space.
* Issue was pointed out by @allyshka
* Fix for #176
> PYTHON3 PATH Fix

- templates/general/index.html
Maximum upload fiel size is set to 100MB
recent ipa are  bigger than this perhaps we could increase to 300 ?
In particular because that's not easy for regular user to find where this value is stored
> upgrade maximum upload file size

- LICENSES/androguard.txt
- StaticAnalyzer/views/android/strings.py
- requirements.txt
Tested on MacOS, Ubuntu, Windows 7 and with Docker image
as requested androguard is installed with pip and not with a git clone 
(ubuntu do have a package)
@ajinabraham need some test 
Comments are welcome
> Replace strings_from_apk.jar with androguard string extraction

- StaticAnalyzer/views/android/manifest_analysis.py
Since we go to Python 3 , the output of the android manifest was not correct due to the byte string output of python3 ( b'<xml  instead of <xml)
#dat = dat.replace(b"\n", b"")
dat = dat.decode()
> Correct Android manisfet xml output

- StaticAnalyzer/views/android/manifest_analysis.py
APktool upgrade to 2.3.2
[#1742] - Android P Preview Support
[#1689] - Initial support for rebuilding with aapt2 binary
[#1730] - Fixed issue with application with empty resources.arsc file
[#1703] - Fixed issue with root depth kotlin folder not copied
[#1741] - Fixed building Apktool on Windows
Added warning if application with non-zero typeIdOffset is discovered
Upgraded baksmali to v2.2.2
Support for treating additional photo extensions (m4a) as raw
Prevent temporary BRUT files from clogging temporary directories
> Update apktool 2.3.2

- StaticAnalyzer/views/android/manifest_analysis.py
update apktool from 2.3.2 to 2.3.3
2018.04.26
Fixed regression with compressing default AOSP filetypes like mp3. (Issue 1769)
Fixed detection of aapt2 builds older than certain SDK versions. (Issue 1774)
> Update apktool to 2.3.3

- MobSF/utils.py
It was hard to run MobSF in the CI - no simple way to control the API key (see #642 ).
Added an option to set API key via env var - `API_KEY`.
> added an option to set api key via env var

- StaticAnalyzer/views/android/strings.py
Fix #687
```
When the method of strings_jar  throw a exception, The MobSF save to database will report an error and cannot be written to database.
```
```
instead of  ['']  , use get() 
```
```
DESCRIBE HERE
```
> fixed get apk strings, change get dict value method

- MobSF/forms.py
- MobSF/rest_api.py
- MobSF/utils.py
```
change the Django form error to
{
"error": {
"file": "This field is required.", 
"test": "This field is required."
}
}
the decorator of request method is easy to use
put the ['get'] or ['post'] on func name
```
```
DESCRIBE HERE
```
```
DESCRIBE HERE
```
> Request method decorator and update form errors

- StaticAnalyzer/views/android/code_analysis.py
- StaticAnalyzer/views/android/manifest_analysis.py
- templates/static_analysis/static_analysis.html
The API of the permission part of Android static analysis is not good enough. The permission field returns a dictionary. The value of the dictionary is a list instead of a dictionary, so the order must be guaranteed. This change may cause historical compatibility issues and requires caution
origin
```
{'android.permission.RECEIVE_BOOT_COMPLETED': ['normal', 'automatically start at boot', 'Allows an application to start itself as soon as the system has finished booting. This can make it take longer to start the phone and allow the application to slow down the overall phone by always running.'}
```
now
```
{'android.permission.RECEIVE_BOOT_COMPLETED': {'status': 'normal', 'info': 'automatically start at boot', 'description': 'Allows an application to start itself as soon as the system has …
```
> change permissons for android to dict

- StaticAnalyzer/views/ios/plist_analysis.py
Fix #699 #686 
```
Info.plist file name of  iOS project is Info.plist
```
```
[INFO] ALL TESTS COMPLETED!
[INFO] Test Status: all tests completed
```
```
DESCRIBE HERE
```
> change ios info plist path

- DynamicAnalyzer/views/android/analysis.py
- StaticAnalyzer/views/android/cert_analysis.py
- StaticAnalyzer/views/android/static_analyzer.py
- StaticAnalyzer/views/shared_func.py
see #735   we have a lot of encoding issue
```
It solve partially a part of the error adding enconding="utf-8" to open 
```
```
BTW I see a lot of encoding="utf8" in the code is it normal ? shouldn't it be utf-8 ?
```
> Fix encoding

- StaticAnalyzer/views/android/manifest_analysis.py
```
The underlying vulnerability is that with ActivityManager.getRecentTasks()
any app with the permission GET_TASKS can read the Intents sent to create
the task. This would reveal the possibly sensitive contents of these Intents.
MobSF warns about Activities using singleTask/singleInstance because these
would be affected by this issue.
According to the Android documentation at https://developer.android.com/reference/android/app/ActivityManager.html#getRecentTasks(int,%20int)
starting with API level 21 it is no longer possible to read all Intents sent
to a root activity by using ActivityManager.getRecentTasks(). After API
level 21, only Intents sent from your own app and other apps to be known
insensitive like the home/launcher app.
See also chapter 4.1.3.3 (page 94) in …
```
> Only warn about singleTask/singleInstance when API level is <21

- StaticAnalyzer/views/android/dvm_permissions.py
Missing Android manifest permission description -> `REQUEST_INSTALL_PACKAGES`.
Added the description in the appropriate file.
Following this PR, probably worth checking if there's anything else missing from [here](https://developer.android.com/reference/android/Manifest.permission.html). I'll scrape this page next time I've got some spare time
> added REQUEST_INSTALL_PACKAGES

- requirements.txt
```
This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
```
So unneeded if using python3, I guess it was when mobsf was in python2.
removes the unneeded dependency
I didn't tested because I don't have a proper setup and I don't want to trash my actual machine by installing last version of mobsf.
> remove configparser

- scripts/clean.sh
must be run only from mobsf directory, otherwise need to manage cases
```
clean script must be run only from MobSF directory otherwise it coudl delete files from other program
```
```
check script path and display error if script not launched from mobSF directory
```
- [X ] Coding style (indentation, etc)
```
replace " with ' for echo cause no variable are displayed 
```
> simplify clean script

- StaticAnalyzer/views/windows.py
Format of json response changed
```
Windows apps static analysis is returning an error.
See Issue #824 .
The format of the response changed.
```
```
Added parsing for the new result.
```
```
BinSkim is installed in version 1.6.0-beta.1 by the setup.py on windows.
Nuget: https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/1.6.0-beta.1
```
> Fix issue #824 - Binary analysis of windows apps failed

- StaticAnalyzer/views/android/manifest_analysis.py
```
Apgrade aoktool to 2.4.0
```
```
[#1893] Updated baksmali/smali to v2.2.6
[#1918] Fixed issue with new restriction with non-empty ids.xml file. (Thanks gino247)
[#1909] Fixed issue with PlatformBuildVersion properties changing to unexpected values. (Thanks gino247)
[#1943] Fixed issue with pending v5 Gradle upgrade, by taking point release v4.10.2. (Thanks Frieder Blumle)
[#1849] Added no-crunch support via new parameters - -nc | --no-crunch. (Thanks Novex)
[#1975] Added automatic tests on Windows environment.
[#1952] Fixed issue when decoding .xsd files between aapt1/aapt2.
[#1976] Fixed issue with decoding applications with a malformed chunk header. (Thanks sebras)
[#1996] Fixed issue with Mac scripts stealing focus.
[#1994, #1922] Fixed issue with array resource bag items having …
```
> Apktool 240

- StaticAnalyzer/views/ios/plist_analysis.py
temporary fix to prevent abort
```
This fix prevent MobSf from generating a 503 and stop analyzing an ipa with plist in json format
#770 
```
```
Must be improved to better handle such case but can be enough for the moment 
```
> correct issue reading plist

- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/ios_binary_analysis.html
```
if VirusTotal reports no problem label must be green, in other cases (analysis not done or something detected) it must be red 
```
```
an improvement could be to use orange label if analysis not done
```
> Better virus total summary

- templates/static_analysis/android_binary_analysis.html
use green colour if no trackers detected also dispkay trackers url as clickable url 
```
If no trackes found in apk we display result with a green label, if trackers found then label is Orange
Trackers URL are clickable
```
> better Trackers stat display

- setup.bat
```
Win64OpenSSL-1_1_1b.exe is not longer available.
Win64OpenSSL-1_1_1c.exe it latest release.
```
> Update openssl download path in setup.bat

- DynamicAnalyzer/views/android/dynamic.py
```
Corrected a typo in DynamicAnalyzer/views/android/dynamic.py
Changed logact.txt to logcat.txt.
Causing dynamic analysis reports to fail as file (logact.txt) did not exist.
```
> Typo corrected - logcat.txt

- MalwareAnalyzer/views/domain_check.py
```
using in instead of startswith will produce false positive example for chrombeta which use 
g.co. if we use in it will match malware url 
```
> Fix malware false positive

- setup.sh
```
Mojave users must install headers, just add a warning cause nobody read the documentation
```
> add warning for mojave and newer version 

- StaticAnalyzer/views/android/code_analysis.py
Static analyzer would skip over classes in sub-packages but it wouldn't skip classes in top-level package.
For example, "okhttp3/OkHttpClient.java" file would still be processed, even though "okhttp3" is in SKIP_CLASSES.
> Fix a bug with checking if package name exist in Android SKIP_CLASSES

- StaticAnalyzer/views/android/android_rules.py
This fixes an issue with "java.util.RandomAccess" being flagged by mistake because it contains "java.util.Random".
> Fix Android insecure Random Number Generator static rule

- .dockerignore
- Dockerfile
```
- Reduce Docker image Size 
- Reorder command to reduce layer
- Reduce Layer
- Silent some command
- Use Static compiled version of Wkhtmltopdf 
- Remove no more needed binaries
```
```
wkhtml static version is downloaded from internet but if needed we can put it in MobSF repo
Docker file is reordered to have a base layer in case we decide to split it 
```
> Reduce Docker image size by replacing wkhtml with static compiled 

- setup.sh
```
For macOS users, some tools must be installed:
- command-line tools
- macOS headers
The setup will now display a message if headers are not there, and provide command to install both tools which are required for setup
```
> Setup: add macOS info

- StaticAnalyzer/views/shared_func.py
```
When extracted urls were converted to lower, we shouldn't do that cause for example filename could be uppercase , and if we test the url we will have a 404 
```
solve #1074
> don't convert URLs to lower

- MalwareAnalyzer/views/Trackers.py
- MobSF/settings.py
Hello there! :)
Replacing the URL of the trackers website with the trackers profile from [εxodus](http://reports.exodus-privacy.eu.org/trackers/)
**Benefits:**
- Shows the code detection which was used to detect the tracker
- Displays additional details about the tracker alongside statistics from εxodus
- Indirectly credits the project which is used to detect trackers
**Example:**
```
- Although the changes are very minor, note that I didn't manage to run the tox linter with the provided documentation
- I changed the settings.py file to make sure the URL is defined only once. Any suggestions are welcome :). 
```
> Replace tracker URL by Exodus tracker URL with more details

- setup.sh
```
on Mojave headers are not installed by default but they are on Catalina so on catalina we only need to check if command line utility is installed 
```
> Make setup.sh  macOS Catalina compliant

- .travis.yml
```
Windows builds were broken due to newer python version I guess. fixed by pinning to Python 3.7.5
```
```
DESCRIBE HERE
```
> Fix build on Windows

- StaticAnalyzer/forms.py
fix #1197 
```
```
```
DESCRIBE HERE
```
> fix form clean method

- README.md
Bug: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1235
See: https://spdx.org/licenses/GPL-3.0-only.html
> Use SPDX identifier for license

- MalwareAnalyzer/views/apkid.py
```
This is a fix to continue analysis on APKiD failure. The failure mostly occurs when dependencies are not installed as recommenced by official docs. Some of our users are bit adventurous on running the setup in ways undocumented.
```
```
DESCRIBE HERE
```
> Bail on APKiD failure

- StaticAnalyzer/views/android/playstore.py
Fixes MobSF/Mobile-Security-Framework-MobSF#1449
Fix `det['privacyPolicy']`
Correct response field from Appmonsta for privacyPolicy is privacy_url
> Fix Appmonsta privacyPolicy response

- StaticAnalyzer/views/android/code_analysis.py
- StaticAnalyzer/views/android/icon_analysis.py
- StaticAnalyzer/views/android/view_source.py
This Pull Request is embedding three things:
- A typo in the `find_icon_path_zip` function, the`starswith()` method does not exist for a string. The author certainly wanted to use the `startswith()` method. There was a crash while Static Analysis on a zipped Android repository, but not blocking.
- During a Static Analysis on a zipped Android repository, only the `.java` files support a "Code Analysis". Kotlin and Java share many functions and it is useful to also analyze `.kt` files.
- Allowing to display kotlin files (`.kt`) on the `ViewSource` feature, this is the same location than java files.
> Fix on Static Analysis on a zipped Android repository

- StaticAnalyzer/views/ios/plist_analysis.py
During the Static Analysis of a zipped iOS project the current configuration only allows the first Info.plist to be analysed.
There is sometimes multiple plist files in a repository and scan them all before compilation can give way more security information.
This Pull Request adds every .plist files to be analysed during a source-code Static Analysis, especially for permissions and ATS.
**Fixtures**:
- Replace 'writePlist()' function by 'dumps()', deprecated in  plistlib>3.4 in `plist_analysis.py` 
- Remove unnecessary 'else' statement in `plist_analysis.py`
> Support multi plist ats/permission analysis during Static Analysis

- StaticAnalyzer/views/ios/rules/ipa_rules.py
- StaticAnalyzer/views/ios/rules/swift_rules.yaml
Caught a couple of spelling / grammatical errors in rule descriptions.
1. "Potential" was misspelled as "potencial"
2. "Makes use of" not "Make use of"
> Fixed Typos

- MobSF/views/api/rest_api.py
- StaticAnalyzer/tests.py
- templates/general/apidocs.html
This will allow users to specifiy a custom header to define the Api Key in conjunction with a `Bearer` authorization. That way when MobSF is behind a reverse proxy or an IdP. The user can send a request as follow: 
```
curl --url "https://fqdn/api/v1/scans" -H "Authorization: Bearer {{MY_IDP_ACCESS_TOKEN}}" -H "X-Mobsf-Api-Key:{{ api_key}}"
```
```
DESCRIBE HERE
```
> Allow specifying a custom header

- StaticAnalyzer/views/ios/code_analysis.py
Fixed #1531 
As of now for iOS source code analysis, MobSF checks for `.swift` files to scan. But if there is a directory named `Name.swift` is also considered as file and trying to read text and fails due to error. Hence I am checking if it's a directory or not and then process. Else skip the directory.
Using `pfile.is_dir()` to check if it's a directory and if True, skip it. More details for why this fix is required check #1531
> Fixed #1531

- StaticAnalyzer/views/android/code_analysis.py
- StaticAnalyzer/views/android/converter.py
```
Windows has a file path restriction in terms of length and characters allowed. Python standard libs like pathlib or shutil can throw exceptions unexpectedly, ignore or skip file on exception and allow scan to complete.
```
```
DESCRIBE HERE
```
> Hide WinError3 in Windows

- setup.bat
```
Bump OpenSSL version since 1.1.1g is not available for download 
```
> Bump OpenSSL Version from 1.1.1g to 1.1.1h

- StaticAnalyzer/views/android/rules/android_rules.yaml
```
Removes the semi-colon from the insecure random regex rule. In Kotlin the semi-colon is not required, and we want to
catch this vulnerability in applications built with Kotlin. https://kotlinlang.org/docs/reference/packages.html#imports
```
```
There should be an issue with past compatibility, and should still apply to java code.
```
> Removing the semi-colon from insecure Random Regex

- mobsf/StaticAnalyzer/views/android/strings.py
Within the static analysis routines for Android Apps, MobSF uses the `is_secret()` method to determine if a string could possibly hold a hardcoded secret. The method uses a list of markers for this.
GitHub scans repositories for secrets and has a pretty decent [documentation](https://docs.github.com/en/github/administering-a-repository/about-secret-scanning) for this. It includes a list of API slugs for many popular APIs. 
Considering this collection, MobSF could add further markers to catch at least most of the API slugs on that list.
Namely, I would like to propose to add the following markers:
* `bearer` (RFC 6749) 
* `jwt` (e.g. *atlassian_jwt*, *frameio_jwt*)
* `certificate `(e.g. *azure_management_certificate*)
* `credential` (e.g. *api_credential_assignment*, *codeship_credential*) …
> [Static Analysis][Android] Improve markers for possible hardcoded secrets

- mobsf/StaticAnalyzer/views/android/binary_analysis.py
Returned string of relro() in mobsf/StaticAnalyzer/views/android/binary_analysis.py not properly checked in line 94 and 102, always leading to the "else" case in line 102 (no matter actual RELRO level of binary, always "No RELRO" is falsely shown).
This pull request fixes these checks accordingly.
- [ OK] Run MobSF unit tests and lint `tox -e lint,test`
- [ Linux] Tested Working on Linux, Mac, Windows, and Docker
- [ - ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
iOS not impacted, as no RELRO there.
> Fix Full RELRO/Partial RELRO/No RELRO check for Android

- mobsf/templates/static_analysis/android_binary_analysis.html
fix typo MANIFIEST > MANIFEST. This typo shows in the APK security reports.
Correct word is "MANIFEST" (https://developer.android.com/guide/topics/manifest/manifest-intro).
```
fix typo MANIFIEST > MANIFEST. This typo shows in the APK security reports.
Correct word is "MANIFEST" (https://developer.android.com/guide/topics/manifest/manifest-intro).
```
- [ x ] Run MobSF unit tests and lint `tox -e lint,test`
- [ x ] Tested Working on Linux, Mac, Windows, and Docker
- [ x ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [ x ] Make sure tests are passing on your PR [![MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/workflows/MobSF%20tests/badge.svg?branch=master)](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)
```
No need to …
```
> fix typo in APK analysis (MANIFIEST > MANIFEST)

- mobsf/StaticAnalyzer/views/ios/plist_analysis.py
A couple minor changes to 
* Prevent the possibility of a TypeError from being raised in `plist_analysis.py` from `is_file_exists`
* Allow a static scan to be saved to the database when the info_plist information does not exist
The following traceback is raised when an "Info.plist" file is not found in the source code:
```
File “/…/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/plist_analysis.py", line 83, in plist_analysis
if not is_file_exists(plist_file):
File "/root/Mobile-Security-Framework-MobSF/mobsf/MobSF/utils.py", line 297, in is_file_exists
if os.path.isfile(file_path):
File "/usr/lib/python3.8/genericpath.py", line 30, in isfile
st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
Given that the logic is to …
> Ensure iOS Static Analysis can complete without Info.plist being present

- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/ios/file_analysis.py
Just adding `der` as supported extension for certificates, as some applications use this extension.
> Support der extension for certificates

- mobsf/StaticAnalyzer/views/comparer.py
- mobsf/templates/static_analysis/compare.html
Comparer is really helpful to analyse differences between applications but it lack some important features.
One of these is the ability to detect differences between browsable activities (deeplinks/universal links) in Android, which is a big attack surface and it can be very interesting to monitor and to detect additions.
Since browsable activities are more complex objects that others (i.e. activities) we need to perform comparison not only on the first level (which browsable activities are in common and which not) but also in deep: from the browsable activities in common, which schemes, hosts, paths are in common and which not?
This PR include a new diffing function for common browsable activities that explore each activity in both apps to detect differences for a set of keys …
> Include browsable activities in comparer

- Dockerfile
`PATH` environment variable will not have `JAVA_HOME` value if it gets set in a single line.
> Fix non-working PATH environment variable

- Dockerfile
- scripts/install_java_wkhtmltopdf.sh
`pip` will update its lists and will not save them if you specify `--no-cache-dir`, and it has to be specified in each `pip install`.
> Add --no-cache-dir to pip install

- mobsf/DynamicAnalyzer/views/android/report.py
```
Fix dynamic report_json api bug, JsonResponse cannot serialize it because runtime_dependencies is set type.
```
- [] Run MobSF unit tests and lint `tox -e lint,test`
```
File "/home/mobsf/Coding/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/core/serializers/json.py", line 106, in default
return super().default(o)
File "/usr/lib/python3.8/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```
> Fix dynamic report_json api bug

- mobsf/StaticAnalyzer/views/android/binary_analysis.py
- mobsf/templates/pdf/android_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
RELRO is causing false positives. Removing it from MobSF binary analysis.
```
DESCRIBE HERE
```
> Remove RELRO from MobSF shared object scan for Android binaries

- mobsf/StaticAnalyzer/views/android/android_manifest_desc.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
Reverts MobSF/Mobile-Security-Framework-MobSF#1905
Causing a lot of false positives
> Revert "Add the checking of the parent element of the permission-related elements to manifest analysis"

- mobsf/StaticAnalyzer/views/ios/macho_analysis.py
```
Fix bug #1917. All details required to understand the changes can be found at: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1917
```
```
Lint tests are failing with a fresh fork for other reasons than this commit
```
> Fix bug #1917 where checking for stripped debugging symbols produces false positives in iOS.

- mobsf/StaticAnalyzer/views/android/static_analyzer.py
Fix the problem that the res resource folder does not exist, the solution is to copy from the apktool_out directory
```
```
```
DESCRIBE HERE
```
> fix res directory not exist

- mobsf/MobSF/init.py
- mobsf/MobSF/urls.py
- mobsf/MobSF/views/home.py
- mobsf/static/landing/css/home.css
- mobsf/templates/base/base_layout.html
- mobsf/templates/general/donate.html
- mobsf/templates/general/home.html
- mobsf/templates/general/recent.html
```
* Warn on mobsf.live that uploads are public
* UI changes
* Self hosted donation page
* Use bootstrap navbar
```
```
DESCRIBE HERE
```
> HOTFIX: UI changes and warning on mobsf.live

- mobsf/MalwareAnalyzer/views/quark.py
```
The path for Quark rules has changed so the previous MobSF version display empty reports.
this hotfix correct the issue
```
> hotfix for quark rules location

- .github/workflows/mobsf-test.yml
- mobsf/StaticAnalyzer/views/android/android_manifest_desc.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- tox.ini
```
Manifest check on minSDK version for android
Test Runner QA
```
```
DESCRIBE HERE
```
> New Android Manifest Rule: App support vulnerable android versions

- mobsf/templates/general/recent.html
```
Filename in static report button link or in the re-scan button is not properly urlencoded. 
When clicking on static report button or re-scan button on the recent scans page you will get an error  if a scanned APK contains an ampersand in the filename.
How to test: Upload an APK with an ampersand in the filename
After the APK has been scanned, go to recent scans and click static report button.
What happens: Error page is displayed (Hash match failed or Invalid file extension or file type)
Example: Xender - Share Music   &    Transfer_12.5.1.Prime_Apkpure.apk
Before fix:
http://0.0.0.0:8000/static_analyzer/?name=Xender%20-%20Share%20Music%20%20%20&%20%20%20%20Transfer_12.5.1.Prime_Apkpure.apk&checksum=f28edeb8c6c07ee9c6500f3c37784817&type=apk
Properly urlencoded: …
```
> Fix for filenames containing ampersand

- mobsf/templates/static_analysis/appsec_dashboard.html
```
The percentage for Info and Secure categories was incorrect. Info and Secure were divided by a total counting two times Warn and zero times High categories.
Fixes also a possible null division.
```
```
No additional comments.
```
> Fix Scorecard Severity Distribution chart data

- mobsf/MobSF/init.py
- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/android/db_interaction.py
- mobsf/StaticAnalyzer/views/android/network_security.py
- mobsf/StaticAnalyzer/views/common/appsec.py
- mobsf/StaticAnalyzer/views/common/suppression.py
- mobsf/StaticAnalyzer/views/ios/db_interaction.py
- mobsf/StaticAnalyzer/views/ios/plist_analysis.py
- mobsf/templates/pdf/android_report.html
- mobsf/templates/pdf/ios_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- mobsf/templates/static_analysis/android_source_analysis.html
- mobsf/templates/static_analysis/ios_binary_analysis.html
- mobsf/templates/static_analysis/ios_source_analysis.html
```
This is a priority enterprise feature request. 
General information area about summary counts for all separate sections in static analysis. For example, after the analysis of the manifest file, showing how many high, how many low, how many information level findings are in a single table. Adding these tables to the PDF report (or any report format already supported within) for each section.
For Android
* Network Security, Certificate Analysis, Manifest Analysis, Code Analysis
For iOS
* App Transport Security, Code Analysis, Binary Code Analysis,
```
```
DESCRIBE HERE
```
> [Enterprise Feature Request EFR02] Support summary of severity in each section.

- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/android/jar_aar.py
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
- poetry.lock
* Add `apksigner.jar`
* Use apksigner to extract signature versions (v1, v2, v3, v4)
* Fix: #2120
```
DESCRIBE HERE
```
> add apksigner.jar for reading signatures

- mobsf/MobSF/init.py
- mobsf/MobSF/urls.py
- mobsf/MobSF/utils.py
- mobsf/StaticAnalyzer/views/android/jar_aar.py
- mobsf/StaticAnalyzer/views/android/so.py
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
- mobsf/StaticAnalyzer/views/common/a.py
- mobsf/StaticAnalyzer/views/common/binary/elf.py
- mobsf/StaticAnalyzer/views/common/binary/lib_analysis.py
- mobsf/StaticAnalyzer/views/common/binary/macho.py
- mobsf/StaticAnalyzer/views/common/shared_func.py
- mobsf/StaticAnalyzer/views/ios/dylib.py
- mobsf/StaticAnalyzer/views/ios/static_analyzer.py
- mobsf/templates/pdf/android_report.html
- mobsf/templates/pdf/ios_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- mobsf/templates/static_analysis/ios_binary_analysis.html
- pyproject.toml
```
* Scan independent library file (.so, .dylib, Framework dylib) from APK/IPA Static Analysis Report
* Library analysis refactored relative path helper for Django template.
* Re-introduced RELRO checks for Android, added Dart binary check to avoid Flutter false positives.
* Improved stripped debug symbol check for ELF and MachO using native OS tools such as nm and objdump when available.
* Merge iOS Framework and Dylib Analysis.
```
```
DESCRIBE HERE
```
> [EFR] QA Request

- mobsf/MobSF/init.py
- mobsf/MobSF/utils.py
- mobsf/MobSF/views/home.py
- mobsf/StaticAnalyzer/tests.py
- mobsf/StaticAnalyzer/views/android/android_manifest_desc.py
- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- mobsf/StaticAnalyzer/views/android/network_security.py
- mobsf/StaticAnalyzer/views/common/binary/macho.py
- mobsf/StaticAnalyzer/views/ios/binary_rule_matcher.py
- mobsf/StaticAnalyzer/views/ios/code_analysis.py
- mobsf/StaticAnalyzer/views/ios/file_analysis.py
- mobsf/StaticAnalyzer/views/ios/rules/swift_rules.yaml
- mobsf/templates/base/base_layout.html
- mobsf/templates/general/about.html
- mobsf/templates/general/apidocs.html
- mobsf/templates/general/home.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- mobsf/templates/static_analysis/android_source_analysis.html
- mobsf/templates/static_analysis/appsec_dashboard.html
- mobsf/templates/static_analysis/ios_source_analysis.html
- pyproject.toml
- scripts/mass_static_analysis.py
```
* Replace Android test APK
* Added tests for Library analysis from binary (scan_library route)
* iOS merge findings from swift and objective c rules with same rule identifier. Fixes #2287 
* iOS Binary analysis, sort regex matches. Fixes #2252
* Framework dylibs with no extensions to skip PIE checks. Fixes #2307
* Select correct network_security config. Fixes #2049
* Android Manifest Analysis added support for detecting task hijacking (StrandHogg 1.0 and StrandHogg 2.0) . Fixes #2124
* Added new manifest analysis rule to warn on apps targeting older Android OS
* Updated severity of findings
* UI improvement for AppSec dashboard to show a loader
* UI changes in Static Analysis to collapse large no of files in API and Code Analysis for better real estate
* Improved certificate file …
```
> Bug Fixes + Improvements

- mobsf/StaticAnalyzer/views/android/code_analysis.py
Fix the issue of unclosed files in Windows system causing unauthorized access to read yaml files.
return yaml.safe_load(file_obj.read_text('utf-8', 'ignore'))
File "C:\Python3\lib\pathlib.py", line 1266, in read_text
with self.open(mode='r', encoding=encoding, errors=errors) as f:
File "C:\Python3\lib\pathlib.py", line 1252, in open
return io.open(self, mode, buffering, encoding, errors, newline,
File "C:\Python3\lib\pathlib.py", line 1120, in _opener
return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\test\\AppData\\Local\\Temp\\tmpclbvrcwq'
```
```
```
DESCRIBE HERE
```
> Windows Python tempfile permission error fix

- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
Using multithreading to improve code efficiency
```
```
```
DESCRIBE HERE
```
> Using multithreading to improve code efficiency

- .github/SECURITY.md
- mobsf/MobSF/init.py
- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/android/icon_analysis.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- poetry.lock
- pyproject.toml
```
* [SECURITY] Fixes an LFI reported by @0x33c0unt - A crafted APK resource with icon name containing arbitrary path will get copied by MobSF as the icon file to the download directory which is available under `/download/` route. Fixed by https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/a58f8a8c0aa49e1581d97e19e8e2255ca96cd838
* Fixes #2324 , Bug in parsing DSA Public Key parameters for fingerprint calculation.
* Update dependencies
```
```
DESCRIBE HERE
```
> [HOTFIX][SECURITY] Fix an LFI, DSA Pub Key parsing bug and dependencies 

- mobsf/StaticAnalyzer/views/android/manifest_utils.py
```
Arbitrary file writes on Windows with apktool fixed with this version
Discovered by [Cl0udG0d](https://github.com/Cl0udG0d?ref=connortumbleson.com) the previous path traversal fix was not hardened when running against Windows. It was learned that Windows will handle both path separators (/ and \) which v2.9.2 had previously isolated to the intended OS. Now cleansing of resource names will include both path separators no matter the OS.
```
> [SECURITY] Fix Arbitrary file writes on Windows

- mobsf/DynamicAnalyzer/views/ios/corellium_apis.py
- mobsf/MobSF/settings.py
Set the default of `MOBSF_CORELLIUM_API_DOMAIN` to `https://app.corellium.com` in `settings.py` as it was not being picked up properly in `dynamic_analyzer.py` for iOS
Several users commented on this issue in Slack
> MOBSF_CORELLIUM_API_DOMAIN Update

- mobsf/templates/base/list.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- mobsf/templates/static_analysis/android_source_analysis.html
- mobsf/templates/static_analysis/ios_binary_analysis.html
- mobsf/templates/static_analysis/ios_source_analysis.html
Most browsers doesn't like rendering thousands/millions of lines if not needed, so wrap (potentially) big lists in `<details>` and auto-open only if they are small (currently below 100 items)
This makes the "static report" page much more responsive for big apps:
> Optimize rendering of big lists

- mobsf/StaticAnalyzer/views/common/binary/elf.py
fix error:
if function.name.endswith('_chk'):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```
```
```
DESCRIBE HERE
```
> Resolve the situation where the function name is bytes

- mobsf/MobSF/init.py
- mobsf/StaticAnalyzer/views/common/shared_func.py
- poetry.lock
- pyproject.toml
```
Positive technologies reported an SSRF vulnerability in MobSF. This PR fixes the same. 
```
```
DESCRIBE HERE
```
> [SECURITY] Fixes an SSRF vulnerability report from positive technologies

- mobsf/MobSF/views/apk_downloader.py
- mobsf/MobSF/views/home.py
```
Check for internet before attempting to download an APK.
```
```
DESCRIBE HERE
```
Fixes: #2405
> Check for internet before attempting to download APK

- mobsf/DynamicAnalyzer/views/common/shared.py
- mobsf/MobSF/init.py
- mobsf/MobSF/urls.py
- mobsf/MobSF/views/api/api_middleware.py
- mobsf/MobSF/views/api/api_static_analysis.py
- mobsf/StaticAnalyzer/views/android/apk.py
- mobsf/StaticAnalyzer/views/common/async_task.py
- mobsf/StaticAnalyzer/views/ios/ipa.py
- mobsf/templates/general/apidocs.html
- pyproject.toml
```
* Async analysis REST API support & Docs
* Fix timeout handle function
* Code QA untar permissions
```
```
DESCRIBE HERE
```
> [4.2.4] Async analysis REST API support, fix timeout handle function, Qa

- mobsf/StaticAnalyzer/views/android/kb/android_manifest_desc.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
Hi again! Another small fix, now manifest parser for android does not store and additional info about intents with high priorities (no intent names or filter schemas), but show all hits in reports:
So just added grouped high_intent_priority_found by priorities and add count of hits in title:
> Save only unique intent priorities in findings

- mobsf/StaticAnalyzer/views/common/appsec.py
Hi guys! Thanks for your work on mobile security!
I'm using appsec section in mobsf report as well structured source of vulns in defectdojo mobsf scorecard [parser](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/mobsf_scorecard/parser.py). After import it looks same as Mobsf Scorecard View:
And for such vulns like this ones:
it is usefull to save list of files with vuln hits as it provided in this render for certs:
So please consider to add rendered list of files to descriptions str for all findings in code analysis section of appsec report.
> Add files list in scorecard desc

- .github/SECURITY.md
- Dockerfile
- mobsf/MobSF/init.py
- mobsf/MobSF/security.py
- mobsf/MobSF/utils.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- mobsf/StaticAnalyzer/views/common/firebase.py
- poetry.lock
- pyproject.toml
```
* Improved SSRF checks (credential checks, length check, port check, path, query, and params check, ipv6, ipv4 coverage, handle possible decimal or hex IP bypasses)
* Add additional strict path check for Applink well known path
* Moved `valid_host` to `security.py`
```
```
DESCRIBE HERE
```
> [SECURITY] Improve SSRF checks, strict path check for well_known_path

- mobsf/StaticAnalyzer/views/android/apk.py
Fixed an issue where the average CVSS score calculation was incorrect due to improper access to the findings key within the JSON structure. The calculation logic was bypassing the findings key and therefore failing to extract valid CVSS scores.
```
This PR fixes a bug where the average CVSS score calculation would always return 0  due to improper JSON traversal.
```
```
DESCRIBE HERE
```
> Correct CVSS calculation by accessing findings key properly

- mobsf/StaticAnalyzer/views/ios/binary_analysis.py
The previous method for locating the executable within an IPA file was failing for apps with spaces in their `.app` bundle name. The logic incorrectly performed a string replacement on the full path of the bundle, resulting in an invalid path to the binary.
This commit refactors the path resolution logic to use `pathlib` features correctly. It now finds the `.app` directory as a `Path` object and uses the `.stem` attribute to reliably determine the executable's name. This approach is more robust, properly handles spaces and special characters in filenames, and avoids fragile string manipulation.
This PR fixes a bug in the iOS static analyzer where binary analysis fails for `.ipa` files containing an `.app` bundle with spaces in its name.
When analyzing an app with a space in its name …
> fix(ios_analyzer): Correctly resolve executable path in .app bundles
