MobSF/Mobile-Security-Framework-MobSF

- Dockerfile
Now, the Dockerfile in the project acts in the same way the docker container you already have in dockerhub. Now it has sqlite client and pdf generator.
> Dockerfile updated. Now with sqlite client and pdf generator

- Dockerfile
I replace MAINTAINER  wich is deprecated with a label and also reduce the number of layers by grouping EN together and also reducing the number of run to install pdf tools
> Dockerfile Cleanup

- Dockerfile
last version is no more in deb format
> upgrade wkhtml to last version 

- Dockerfile
same erros as kali so need to apply kali patch when building image
> solve error in docker container

- StaticAnalyzer/views/android/static_analyzer.py
- templates/static_analysis/static_analysis.html
Once done, the dynamic results should be accessible again
> Saving the dynamic results

- .gitignore
- Dockerfile
Changes on Dockerfile to keep it updated.
> Dockerfile maintenance

- MobSF/settings.py
- StaticAnalyzer/views/android/VirusTotal.py
I think it could be fien to prevent upload to virus total if apk is not in database , but grab the report if in it
> Add a label to prevent upload

- Dockerfile
17.04 is no more supported by ubuntu need to migrate to 17.10
> update ubuntu version

- StaticAnalyzer/views/android/manifest_analysis.py
> Python3 update apktool

- templates/general/about.html
add more info about MobSF and what it can do
> update about page

- MalwareAnalyzer/views.py
- MobSF/settings.py
- MobSF/utils.py
- StaticAnalyzer/views/android/VirusTotal.py
Add Upstream Proxy support to all network calls.
> Superpoussin22 Python3 Upstream proxy

- Dockerfile
Enable and configure APKiD in Dockerfile
By @superpoussin22
> Dockerfile with APKiD enabled

- StaticAnalyzer/views/android/manifest_analysis.py
read AndroidManifest.xml for apktool if file exist
> Fix manifest reading

- StaticAnalyzer/views/android/icon_analysis.py
- StaticAnalyzer/views/android/static_analyzer.py
use Androguard to get icon , sounds to solve icon issue in particular on mac
> Get icon androguard python3

- MalwareAnalyzer/views.py
- StaticAnalyzer/views/android/static_analyzer.py
analyse apk also with apkid to detect obfuscator for exemple
> Better apkid

- Dockerfile
- README.md
```
No problem, just to keep updated
```
```
Now Last stable Ubuntu is used (18.04 Bionic Beaver)
```
- [X ] Run MobSF unit tests
```
The tests were fine.
```
> Dockerfile updated

- requirements.txt
> update androguard to 3.2.1

- Dockerfile
no more generic tar.gz version so using the deb file
> update pdf generator

- MobSF/rest_api.py
- MobSF/rest_api_middleware.py
- MobSF/settings.py
```
Using middleware is more unified and standardized
Django has a limit on the size of the file upload, increasing the size
```
```
DESCRIBE HERE
```
```
DESCRIBE HERE
```
> Add Auth Middleware

- MalwareAnalyzer/views.py
- StaticAnalyzer/views/android/static_analyzer.py
```
some APKID results not reported DESCRIBE HERE
```
```
It analyze dex and also apk 
```
```
It require optimization I think , in views.py
```
> Correct apkid result

- scripts/mobsfy.py
```
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/662
```
```
Use CapFuzz root CA
Also Code QA
```
```
DESCRIBE HERE
```
> Fixed a Regression Bug

- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/static_analyzer.py
```
DESCRIBE HERE
```
```
DESCRIBE HERE
```
```
DESCRIBE HERE
```
> Get the executable file name from the info.plist

- MobSF/settings.py
```
Yara installation instruction in settins.py are wrong so I correct it 
```
> correct instruction for yara

- Dockerfile
- MobSF/urls.py
- MobSF/utils.py
- MobSF/views/api/rest_api.py
- MobSF/views/helpers.py
- MobSF/views/home.py
- StaticAnalyzer/tests.py
- requirements.txt
- run.bat
- run.sh
- setup.bat
- setup.sh
```
REST API Unit test was broken. Since there was two test URLs, we missed running all of the tests. 
```
```
Now we run all the tests and uses django's unittest case
Simplified Install and Setup
Automated tests on Docker build at DockerHub
```
```
Now you can run tests like
//Run all tests
python manage.py test
//Run individual tests
python manage.py test StaticAnalyzer.tests.StaticAnalyzerAndAPI.test_rest_api
python manage.py test StaticAnalyzer.tests.StaticAnalyzerAndAPI.test_static_analyzer
```
> Fixed Tests, Run tests like normal Django Apps, Simplified Setup, Install and Automated unit tests in Dockerfile

- templates/pdf/ios_binary_analysis_pdf.html
- templates/static_analysis/ios_binary_analysis.html
> fixed_ios_binary_analysis_color

- setup.bat
```
Openssl new link 1.1.1a
```
> update link for openssl windows

- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/db_interaction.py
- StaticAnalyzer/views/ios/static_analyzer.py
- templates/pdf/ios_binary_analysis_pdf.html
- templates/pdf/ios_source_analysis_pdf.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
Remove Html content for iOS fileAnalysis
> change iOS fileAnalysis data struct

- MobSF/settings.py
- StaticAnalyzer/views/android/converter.py
Skip classes update + cfr silent flag
> Skip classes update + cfr silent flag

- StaticAnalyzer/views/ios/view_source.py
Plist file will be garbled if it is read directly
> fix viewsource for plist file format

- MobSF/views/home.py
- templates/general/apidocs.html
If it does not exist, it should return a non-existent state
> support deleted not found tips

- Dockerfile
- MobSF/utils.py
```
Java 11 is now the LTS version for Java , so the dockerfile need to be updated
```
```
It add Java 11 in the image
```
```
None
```
> Move to JAVA 11 in Docker File

- StaticAnalyzer/views/android/manifest_analysis.py
```
The data structure is more reasonable, and new fields have been added to indicate which problem
```
```
DESCRIBE HERE
```
```
DESCRIBE HERE
```
> manifest add key

- MobSF/settings.py
- StaticAnalyzer/views/android/code_analysis.py
- StaticAnalyzer/views/android/converter.py
- requirements.txt
```
* Colored Logs
* Log Clean up
* Disable Log Propagation
```
```
DESCRIBE HERE
```
> Colored Logs + Log Clean up

- setup.bat
New direct url to download OpenSSL, old url is down
```
```
```
DESCRIBE HERE
```
> OpenSSL new url

- templates/pdf/static_analysis_pdf.html
- templates/static_analysis/static_analysis.html
```
add VirusTotal Score on top with CVSS 
```
> add Virus_total Score for apk

- StaticAnalyzer/models.py
- StaticAnalyzer/views/android/db_interaction.py
- StaticAnalyzer/views/android/playstore.py
- StaticAnalyzer/views/android/static_analyzer.py
- StaticAnalyzer/views/ios/appstore.py
- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/db_interaction.py
- StaticAnalyzer/views/ios/static_analyzer.py
- requirements.txt
- templates/pdf/ios_binary_analysis_pdf.html
- templates/pdf/ios_source_analysis_pdf.html
- templates/pdf/static_analysis_pdf.html
- templates/pdf/static_analysis_zip_pdf.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
- templates/static_analysis/static_analysis.html
- templates/static_analysis/static_analysis_android_zip.html
```
* List details from google play store for android apk and zip
* iOS IPA and ZIP App Store Details
```
```
DESCRIBE HERE
```
> Added Playstore & App Store Information

- Dockerfile
- MobSF/settings.py
- MobSF/wsgi.py
- StaticAnalyzer/views/android/playstore.py
- StaticAnalyzer/views/ios/appstore.py
- requirements.txt
- run.sh
```
* Move from Django dev server to Gunicorn prodserver
* Better performance for over all response time
```
> Default Django Dev Server ^
> Gunicorn Prod Server ^
> Better PDF Rendering times with Gunicorn ^
```
DESCRIBE HERE
```
> Moving to Gunicorn prod server: Perf improvements

- MobSF/urls.py
- MobSF/views/api/rest_api.py
- MobSF/views/home.py
- StaticAnalyzer/tests.py
- StaticAnalyzer/views/android/static_analyzer.py
- StaticAnalyzer/views/ios/static_analyzer.py
- StaticAnalyzer/views/shared_func.py
- StaticAnalyzer/views/windows.py
- templates/general/apidocs.html
- templates/general/recent.html
implement #888 
```
```
```
DESCRIBE HERE
```
> support recent scans api

- README.md
Fixed typo in Line:106. 'inspierd' -> 'inspired'. 😄
```
-- Minor. Fixed typing error on Line 106 in README.md.
```
```
```
> Fixed typing error

- Dockerfile
```
fix decode utf-8 issue
Fix #905  
```
fix #905 
```
DESCRIBE HERE
```
> fixe  utf-8 issue

- MalwareAnalyzer/views/apkid.py
- MobSF/settings.py
- MobSF/views/api/rest_api.py
- StaticAnalyzer/views/shared_func.py
- requirements.txt
- run.bat
```
* Re enabled APKiD
* APKiD is available by default
* Bug Fix: PDF clobbering variable
```
```
DESCRIBE HERE
```
> Hotfix: Re enable APKiD, PDF exception handling, APKiD enabled by default

- StaticAnalyzer/views/android/icon_analysis.py
```
if app icon is an adpative icon then an xml file is returned as icon , so in this case we will try to guess the app icon
```
> handle adaptive icon

- requirements.txt
- run.bat
- setup.bat
- setup.sh
```
* Clean up and improve setup
* Enable Windows Support
```
```
DESCRIBE HERE
```
> Setup Tweak, Enable Windows Support.

- templates/pdf/android_binary_analysis.pdf.html
- templates/static_analysis/android_binary_analysis.html
```
Add Trackers summary in app score
```
> Add trackers summary

- README.md
```
Reflect correct version in Readme
```
> Bump version in Readme from 1.0 to 1.1

- MalwareAnalyzer/views/apkid.py
Hotfix for new APKiD 2.0.3
Ran all the tests.
> Support for APKiD 2.0.3

- requirements.txt
```
add apkid 2.0.3
hotfix after change from previous PR 
```
> update to apkid203

- scripts/clean.sh
- scripts/kali_fix.sh
```
simple code cleaning add shebang to shell scripts
```
> Code qa shebang

- StaticAnalyzer/views/comparer.py
- templates/static_analysis/compare.html
Fixes the bug in the app compare with the new structure of the APKiD 
```
DESCRIBE HERE
```
> Support the new apkid for the app compare

- .travis.yml
- DynamicAnalyzer/tools/webproxy.py
- install/windows/setup.py
11 undefined names found:
```
https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/builds/116968308#L734
```
```
DESCRIBE HERE
```
> Travis CI: Add flake8 tests to find undefined names

- StaticAnalyzer/models.py
- StaticAnalyzer/views/android/db_interaction.py
- StaticAnalyzer/views/android/static_analyzer.py
- templates/pdf/android_binary_analysis.pdf.html
- templates/pdf/android_source_analysis_pdf.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
```
By default, the file name and package name are displayed, and the name of the application is not displayed.
```
```
```
> support display app name for android

- requirements.txt
```
update withenois to 4.1.3
```
> update whitenoise to 4.1.3

- MobSF/utils.py
```
Blocking the application when it is accessed in a network-restricted area, so it should be executed asynchronously
```
```
DESCRIBE HERE
```
> check update in another thread

- scripts/mass_static_analysis.py
```
a little typo prevent script from running
```
> correct typo in mass static script

- setup.bat
- setup.sh
```
Feature request: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1017
```
```
DESCRIBE HERE
```
> move to python3 venv

- requirements.txt
```
Upgrade Django to 2.2.4
```
> upgrade Django to 2.2.4

- MobSF/utils.py
```
Fix an issue where check update reports there's an update for MobSF when user do have the last version
```
> fix check_update error

- .travis.yml
- Dockerfile
- setup.bat
- setup.sh
- tox.ini
```
Optimized Travis
Travis now runs test on Mac and Linux
Improved Setup
Updated yara-python install for APKiD
```
```
DESCRIBE HERE
```
> HOTFIX: optimize travis, update setup and optimize apkid install

- .github/CONTRIBUTING.md
```
Use same display as PR ...
```
> open bug as url

- StaticAnalyzer/views/android/playstore.py
- requirements.txt
- templates/pdf/android_binary_analysis.pdf.html
- templates/pdf/android_source_analysis_pdf.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
```
Replace play-scraper which sounds no more maintained by google-play-scraper
```
> replace play-scraper with google-play-scraper

- StaticAnalyzer/views/android/converter.py
```
Hide all jadx warning
```
```
DESCRIBE HERE
```
> Reduce jadx noise

- .dockerignore
- Dockerfile
```
Disable caching of pip packages and also wheel
Reduce number of layers
add a .dockerignore cause some files are not needed in the docker image
```
> reduce Docker image size

- StaticAnalyzer/views/android/playstore.py
- templates/pdf/android_binary_analysis.pdf.html
- templates/pdf/android_source_analysis_pdf.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
```
Add Google Plastore Description
Add Privacy Link
```
> Add Google Playstore Description

- StaticAnalyzer/views/windows.py
- install/windows/rpc_client.py
```
Revert changes to support latest binskim
```
```
DESCRIBE HERE
```
> HOTFIX: windows revert to support latest binskim

- StaticAnalyzer/views/android/converter.py
- StaticAnalyzer/views/ios/binary_analysis.py
```
iOS improve Binary Analysis Accuracy
```
```
DESCRIBE HERE
```
> Peja iOS improve Binary Analysis

- templates/pdf/android_binary_analysis.pdf.html
- templates/static_analysis/android_binary_analysis.html
```
add a message saying no issue found for android binary analysis if nothing bad found.
by default it was empty, so user think MobSF didn't find the lib in the apk 
```
> add info for binary analysis

- .travis.yml
- StaticAnalyzer/views/windows.py
- install/windows/setup.py
```
Takes approx 14 minutes for Windows Tests
Disable binskim and binscope in CI environment
No Linting at the moment.
TODO: Support binskim & binscope in CI
```
```
DESCRIBE HERE
```
> Added Windows to Travis tests

- MalwareAnalyzer/views/domain_check.py
```
Preivous method produce False-Positive. 
This new version normalize also url in apk to extract the domain the right way 
```
> Quick fix malware detection Bug

- .travis.yml
- Dockerfile
- requirements.txt
- setup.bat
- setup.sh
```
Refactored setup as per #1093 
APKiD is causing segfault. 
```
```
DESCRIBE HERE
```
> HOTFIX: Refactor Setup and remove APKiD

- DynamicAnalyzer/views/android/environment.py
- requirements.txt
```
Update Frida to 12.7.5
```
> Update Frida to 12.7.5

- Dockerfile
- MobSF/utils.py
- scripts/kali_fix.sh
```
We don't need it anymore. since we removed bundled adb.
```
```
DESCRIBE HERE
```
> Remove Kali Fix

- MobSF/settings.py
- StaticAnalyzer/views/android/android_rules.py
- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/ios_rules.py
- StaticAnalyzer/views/shared_func.py
- templates/pdf/android_binary_analysis.pdf.html
- templates/pdf/android_source_analysis_pdf.html
- templates/pdf/ios_binary_analysis_pdf.html
- templates/pdf/ios_source_analysis_pdf.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
```
OWASP Mobile Top 10 2016 Support and Better App Security Scoring
```
```
DESCRIBE HERE
```
> OWASP Mobile Top 10 2016 support and better App Security scoring

- requirements.txt
ensure we have the right version to work with oscrypto
```
ensure we have the right version of asn1crypto to work with oscrypto (in particular for MacOS
```
> add asn1crypto as requirement

- MalwareAnalyzer/views/apkid.py
```
One user got issue so reverting for the moment 
```
- [X ] Run MobSF unit tests and lint `tox -e lint,test`.
```
DESCRIBE HERE
```
> revert apkid 2.1.0 support

- setup.bat
> Update setup.bat to fix broken link

- DynamicAnalyzer/views/android/environment.py
- requirements.txt
```
Frida Server Android is updated to 12.7.11
Requirements:
Frida is updated to 12.7.11 
lxml to 4.4.1
asn1crypto to 1.2.0
oscrypto to 1.1.0
```
```
Windows not tested 
```
> Update Frida and Requirements

- MobSF/settings.py
- MobSF/utils.py
- requirements.txt
```
platform.dist() is deprecated. Replaced it with the suggested distro module
```
```
DESCRIBE HERE
```
> Replace platform.dist() with distro.linux_distribution()

- MobSF/utils.py
replace dist tupple by a string
```
Better display of Distro
Dist: ('darwin', '19.0.0', '')  => Dist: darwin 19.0.0
```
> Update utils.py for Distro

- .travis.yml
- Dockerfile
- MobSF/settings.py
- requirements.txt
- setup.bat
- setup.sh
> Enable APKiD by default

- Dockerfile
- MobSF/utils.py
- docker-compose.yml
```
- Fixed typo in docker-compose.yml
- Updated Dockerfile to install requirements before copying source code. This one dramatically decreases image rebuild time
- Added option to override secret key using environment variable. As of now, secret file is created upon image build. As a result, secret is the same for all installations
```
```
DESCRIBE HERE
```
> Improvements to MobSF Docker installation

- README.md
python 3.7 badge
```
Replace Python 3.6 Badge with Python 3.7 Badge
```
```
DESCRIBE HERE
```
> Python 3.7 Badge

- requirements.txt
```
update django colorlog asn1crypto and macho
```
> update django colorlog asn1crypto and macho

- DynamicAnalyzer/views/android/environment.py
- requirements.txt
```
Update frida to 12.8.9 
```
> Update frida to 12.8.9

- LICENSES/IP2LOCATION LITE DATA.txt
- MalwareAnalyzer/views/domain_check.py
- MobSF/settings.py
- MobSF/utils.py
- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/db_interaction.py
- StaticAnalyzer/views/ios/file_analysis.py
- StaticAnalyzer/views/ios/file_recon.py
- StaticAnalyzer/views/ios/otool_analysis.py
- StaticAnalyzer/views/ios/static_analyzer.py
- requirements.txt
- templates/dynamic_analysis/android/dynamic_report.html
- templates/pdf/android_binary_analysis.pdf.html
- templates/pdf/android_source_analysis_pdf.html
- templates/pdf/ios_binary_analysis_pdf.html
- templates/pdf/ios_source_analysis_pdf.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
```
* We didn't do URL and Email extraction from IPA. This PR adds support for extracting URLs and EMAILs from files and strings dump from IPA.
* Also adds IP to GeoLocation - IP to Geolocation
```
```
DESCRIBE HERE
```
> IPA Analysis to support URL and Email Extraction, IP to Geolocation

- .travis.yml
- Dockerfile
- MalwareAnalyzer/views/apkid.py
- requirements.txt
- setup.bat
- setup.sh
```
Update apkid to 2.1.0 ( it does also includ enew detection rules)
```
> update apkid to 2.1.0

- MobSF/settings.py
- static/others/css/pdf_report.css
- templates/pdf/android_report.html
- templates/pdf/ios_report.html
```
App Security Score and Risk Calculation description is added to the end of the pdf report.
A new severity CRITICAL is also added.
```
```
DESCRIBE HERE
```
> App Security Score and Risk Calculation

- MalwareAnalyzer/views/domain_check.py
quick-fix
```
if url contain a port the geolocation did not work 
quick fix 
```
```
DESCRIBE HERE
```
> Remove url port for Geolocation

- StaticAnalyzer/views/ios/permission_analysis.py
###Add faceid usage in permission analysis
```
Add faceid usage in permission analysis
```
> iOS: Add faceid usage in permission analysis

- install/windows/setup.py
```
Fix a setup bug in windows.
```
Fixes: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1290
```
DESCRIBE HERE
```
> Fix Windows Setup bug

- .travis.yml
```
Fix Travis Windows
```
```
DESCRIBE HERE
```
> Update to JDK 13.0.2 in Travis Windows

- StaticAnalyzer/views/ios/app_transport_security.py
- templates/pdf/ios_report.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
```
Updated/added code to reflect Apple's iOS general ATS checks and domain exceptions as documented on their developer website. The following new properties/keys have been added:
- NSAllowsLocalNetworking
- NSExceptionAllowsInsecureHTTPLoads
- NSExceptionMinimumTLSVersion
- NSExceptionRequiresForwardSecrecy
- NSRequiresCertificateTransparency
Reporting templates have been updated as well.
```
> Updated iOS App Transport Security (ATS) general checks, domain exceptions and reporting

- StaticAnalyzer/views/ios/app_transport_security.py
- templates/pdf/ios_report.html
- templates/static_analysis/ios_binary_analysis.html
- templates/static_analysis/ios_source_analysis.html
```
- iOS Application Transport Security Improvements by @shanilprasad
- Reduced False Positives
- Add new Checks
```
Thanks to @rajuraju14
```
DESCRIBE HERE
```
> Improved iOS ATS Checking 

- DynamicAnalyzer/tools/frida_scripts/default/api_monitor.js
- DynamicAnalyzer/tools/frida_scripts/default/root_bypass.js
- DynamicAnalyzer/views/android/dynamic_analyzer.py
- DynamicAnalyzer/views/android/environment.py
- MobSF/settings.py
- MobSF/utils.py
- templates/dynamic_analysis/dynamic_analysis.html
```
* Support Android Emulator AVD x86, ARM, ARM64
* Optimize Root Checking Frida Script
* Environment Checks to see if API Level is supported and /system is writable
* Fixed API Monitor which was broken in frida 12.8.19
```
```
ARM emulator ARM tested on windows
```
> Support Android Emulator AVD x86, ARM, ARM64, Fix Frida Scripts and added env checks

- StaticAnalyzer/views/ios/app_transport_security.py
```
Fixes #1344
```
```
DESCRIBE HERE
```
> Fixes #1344

- MobSF/settings.py
- StaticAnalyzer/views/android/code_analysis.py
- StaticAnalyzer/views/android/rules/android_apis.py
- StaticAnalyzer/views/android/rules/android_rules.py
- StaticAnalyzer/views/ios/binary_analysis.py
- StaticAnalyzer/views/ios/code_analysis.py
- StaticAnalyzer/views/ios/rules/common_rules.py
- StaticAnalyzer/views/ios/rules/ios_apis.py
- StaticAnalyzer/views/ios/rules/ipa_rules.py
- StaticAnalyzer/views/ios/rules/objc_rules.py
- StaticAnalyzer/views/ios/rules/swift_rules.py
- StaticAnalyzer/views/sast_core/matchers.py
- StaticAnalyzer/views/sast_core/rule_matchers.py
- StaticAnalyzer/views/sast_core/standards.py
- StaticAnalyzer/views/shared_func.py
> HOTFIX: Code QA + Version Bump

- templates/pdf/android_report.html
- templates/pdf/ios_report.html
- templates/pdf/windows_report.html
> Add background color to PDF report

- README.md
> add zh-cn for README.md

- .gitattributes
- DynamicAnalyzer/views/android/environment.py
- scripts/update_frida.py
```
Support Genymotion Cloud
```
```
DESCRIBE HERE
```
> Genymotion Cloud Support

- DynamicAnalyzer/views/android/environment.py
- requirements.txt
```
Update rsa to 4.6 
Update Frida to 12.9.7
```
> update rsa to 4.6 and frida to 12.9.7

- DynamicAnalyzer/views/android/dynamic_analyzer.py
This PR introduces no new functionality.
> fix typo in dynamic analyzer log

- MobSF/views/api/rest_api.py
> use set instead list

- StaticAnalyzer/views/shared_func.py
- templates/pdf/android_report.html
- templates/pdf/ios_report.html
- templates/pdf/windows_report.html
Add Scan Date to PDF reports.
Close MobSF/Mobile-Security-Framework-MobSF#1395
> Add Scan Date to PDF reports

- DynamicAnalyzer/views/android/environment.py
- MobSF/settings.py
- templates/dynamic_analysis/dynamic_analysis.html
```
Fixes a bug #1502 in Windows on Dynamic Analysis APK install verification
Added Support for Android 10 API 29 for Genymotion
```
```
DESCRIBE HERE
```
> Hotfix: Windows DM Install Verify and Android 10 Support

- StaticAnalyzer/models.py
- StaticAnalyzer/views/android/db_interaction.py
- StaticAnalyzer/views/android/static_analyzer.py
- StaticAnalyzer/views/android/strings.py
- templates/pdf/android_report.html
- templates/static_analysis/android_binary_analysis.html
```
Extract Hardcoded Secrets from Android APK String Resource
```
```
DESCRIBE HERE
```
> Hardcoded Secrets

- DynamicAnalyzer/views/android/environment.py
- requirements.txt
```
update frida to 12.11.10
update libsast to 1.1.6
```
```
none
```
> update frida to 12.11.10 and libsast to 1.1.6

- README.md
> Update README - Source Tree

- StaticAnalyzer/views/android/manifest_analysis.py
```
Update apktool to 2.5.0 
https://connortumbleson.com/2020/12/02/apktool-v2-5-0-released/
```
> Apktool 2.5.0

- MalwareAnalyzer/views/domain_check.py
- MobSF/settings.py
- StaticAnalyzer/views/android/manifest_analysis.py
- StaticAnalyzer/views/android/rules/android_niap.yaml
- static/others/css/pdf_report.css
- templates/pdf/android_report.html
- templates/static_analysis/android_binary_analysis.html
- templates/static_analysis/android_source_analysis.html
```
Upgrade NIAP
Fixed #1563, #1556, #1617
```
```
DESCRIBE HERE
```
> NIAP 1.2 - > 1.3, Permission Analysis QA

- DynamicAnalyzer/views/android/frida_core.py
- DynamicAnalyzer/views/android/frida_scripts.py
- DynamicAnalyzer/views/android/tests_frida.py
- DynamicAnalyzer/views/android/tests_xposed.py
- MobSF/settings.py
- MobSF/views/api/api_static_analysis.py
- MobSF/views/helpers.py
- MobSF/views/home.py
- MobSF/views/scanning.py
- README.md
- StaticAnalyzer/tests.py
- StaticAnalyzer/views/android/static_analyzer.py
- StaticAnalyzer/views/android/xapk.py
- templates/general/apidocs.html
- templates/general/home.html
- templates/general/recent.html
```
Check for ZIP Magic on Upload
Support XAPK file format. (Please note that we only scans base APK at this time)
Windows utf-8 safe reads,  handle frida exceptions
Tests for XAPK
Fixes: #1573, #1517
```
```
DESCRIBE HERE
```
> HOTFIX: Zip magic check, XAPK support, QA

- mobsf/MobSF/settings.py
- mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml
- mobsf/StaticAnalyzer/views/ios/rules/objective_c_rules.yaml
- mobsf/StaticAnalyzer/views/ios/rules/swift_rules.yaml
- mobsf/signatures/maltrail-malware-domains.txt
- mobsf/templates/pdf/android_report.html
- mobsf/templates/pdf/ios_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- mobsf/templates/static_analysis/android_source_analysis.html
- mobsf/templates/static_analysis/ios_source_analysis.html
```
Added OWASP MSTG Mapping to all rules
```
```
DESCRIBE HERE
```
> OWASP MSTG Mapping to all rules

- mobsf/StaticAnalyzer/views/android/android_manifest_desc.py
- mobsf/StaticAnalyzer/views/android/binary_analysis.py
- mobsf/StaticAnalyzer/views/android/network_security.py
- mobsf/StaticAnalyzer/views/ios/macho_analysis.py
Thank you very much for this awesome tool 🙂
I encountered a few minor typos that are addressed with this pull request.
> Fix minor typos

- setup.sh
```
Clean setup script for Macos 
Remove unneeded  check and tools
```
```
if Ok need to clean documentation too
```
> cleanup setup script for mac

- .github/workflows/auto-comment.yml
- Dockerfile
- README.md
- mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
- mobsf/MalwareAnalyzer/views/VirusTotal.py
- mobsf/MobSF/init.py
- mobsf/MobSF/settings.py
- mobsf/MobSF/utils.py
- mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
- mobsf/StaticAnalyzer/views/android/strings.py
- mobsf/StaticAnalyzer/views/ios/static_analyzer.py
- mobsf/StaticAnalyzer/views/windows/windows.py
- mobsf/install/windows/readme.md
- mobsf/install/windows/setup.py
- mobsf/signatures/maltrail-malware-domains.txt
- mobsf/templates/dynamic_analysis/dynamic_analysis.html
- scripts/entrypoint.sh
- scripts/postgres_support.sh
- setup.py
```
* Move Version to init.py
* Default to Use HOME from MobSF v3.4
* Update Checking improvement
* New Android Rule AES ECB Default
* Update all code locations to dynamically detect config/settings location.
* Rescan Code QA Re: #1670
```
```
DESCRIBE HERE
```
> HOTFIX: Move Version and Default to Use HOME

- Dockerfile
- scripts/postgres_support.sh
This fixes issue  #1737 (Dockerfile not building container due to path issue). 
The script `postgress_support.sh` needs to be run from within `./scripts` directory.
> fixing issue settings.py not found from postgress_support.sh script

- LICENSES/FSecureLabs_frida_scripts.txt
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/fingerprint_bypass.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/fingerprint_bypass_via_exception_handling.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/keyguard_credential_intent.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/tracer_cipher.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/tracer_keygenparameterspec.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/tracer_keystore.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/others/tracer_secretkeyfactory.js
- mobsf/templates/dynamic_analysis/android/dynamic_analyzer.html
```
Credits to: https://github.com/FSecureLABS/android-keystore-audit/tree/master/frida-scripts
FSecureLabs_frida_scripts.txt
frida_scripts/others/fingerprint_bypass.js
frida_scripts/others/fingerprint_bypass_via_exception_handling.js
frida_scripts/others/keyguard_credential_intent.js
frida_scripts/others/tracer_cipher.js
frida_scripts/others/tracer_keygenparameterspec.js
frida_scripts/others/tracer_keystore.js
frida_scripts/others/tracer_secretkeyfactory.js
```
```
DESCRIBE HERE
```
> New Frida Scripts from FSecureLabs

- mobsf/MobSF/init.py
- mobsf/MobSF/settings.py
- mobsf/StaticAnalyzer/views/common/appsec.py
- mobsf/StaticAnalyzer/views/ios/permission_analysis.py
- mobsf/StaticAnalyzer/views/ios/view_source.py
- mobsf/static/others/css/pdf_report.css
- mobsf/templates/pdf/android_report.html
- mobsf/templates/pdf/ios_report.html
- mobsf/templates/static_analysis/appsec_dashboard.html
- mobsf/templates/static_analysis/ios_binary_analysis.html
- mobsf/templates/static_analysis/ios_source_analysis.html
```
* Enterprise feature request EFR01
* Added hotspots section
* For non EFR01 users, hostspot contains information from permissions and file analysis.
* Renamed Warning to Medium
* iOS View Source QA
* iOS Permissions QA
```
```
DESCRIBE HERE
```
> HOTFIX: EFR01 Enterprise feature request

- requirements.txt
```
Update Quark and Frida
```
> update quark & frida

- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
```
Update APKTOOL to 2.6.1
- Begin options refactor by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/2648
- fix: decoding references to private resources by @MrIkso in https://github.com/iBotPeaches/Apktool/pull/2650
- fix: support for signature scheme v4 by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/2705
- Replace use of deprecated methods with their recommended replacements by @alsutton in https://github.com/iBotPeaches/Apktool/pull/2713
- Update dependencies by @Goooler in https://github.com/iBotPeaches/Apktool/pull/2715
- Cleanup trailing temp files/folders by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/2742
- fix: prevent file hold on tmpDir during build by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/2745
- refactor: …
```
> upgrade apktool to 2.6.1

- mobsf/MobSF/settings.py
- mobsf/StaticAnalyzer/views/android/generate_downloads.py
- mobsf/templates/static_analysis/ios_binary_analysis.html
Fixes https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1932
Show IPA download button for iOS binary analysis results page.
Make the UI look similar
```
DESCRIBE HERE
```
> Feature Parity Allow iOS IPA download

- .github/workflows/mobsf-test.yml
- mobsf/StaticAnalyzer/views/ios/rules/objective_c_rules.yaml
- requirements.txt
```
HOTFIX: libsast, iOS Rule, M1 Mac support
```
```
DESCRIBE HERE
```
> HOTFIX: libsast, iOS Rule, M1 Mac support

- README.md
add Badge App
```
Add the BadgeApp in readme , openssf best Practices
```
> Add BadgeApp to  README.md

- requirements.txt
> update apkid to 2.1.4

- mobsf/MobSF/init.py
- mobsf/static/others/js/suppression.js
- mobsf/templates/pdf/android_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
```
* Split Certificate analysis in android as a separate section.
* Suppression listing edge case fix
```
```
DESCRIBE HERE
```
> Split certificate analysis out, suppression list fixes

- scripts/check_install.py
```
Solving a misspelling issue, changed "installtion" to "installation";
Should not affect anything regarding functional code.
```
```
NONE
```
> Installation script error: Solving spelling error

- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
```
Update Apktool to 2.7.0
https://github.com/iBotPeaches/Apktool/releases/tag/v2.7.0
```
> Apktool 2.7.0 update

- requirements.txt
Fixes #2134 
```
DESCRIBE HERE
```
> HOTFIX - Fix broken docker builds

- Dockerfile
- tox.ini
```
Install jq in dockerfile for scripting capabilities
```
```
DESCRIBE HERE
```
> HOTIX: Update Dockerfile to install jq

- mobsf/MobSF/init.py
- mobsf/MobSF/settings.py
- mobsf/StaticAnalyzer/views/android/binary_analysis.py
- mobsf/StaticAnalyzer/views/android/code_analysis.py
- mobsf/StaticAnalyzer/views/android/converter.py
- mobsf/StaticAnalyzer/views/sast_engine.py
- requirements.txt
- run.bat
- run.sh
* Address https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1889
* Add support for environment variables in config. In order for this to work, existing configs must be updated or deleted. 
* Supported config env vars are available in `mobsf/MobSF/settings.py`
* Fixes #2109
```
DESCRIBE HERE
```
> [HOTFIX] Add support for environment variable for MobSF config

- README.md
- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
```
Android min SDK check on janus vulnerability detection 
```
```
DESCRIBE HERE
```
> HOTFIX: Android min SDK check on janus vulnerability detection

- .github/workflows/mobsf-test.yml
- Dockerfile
- mobsf/DynamicAnalyzer/tools/webproxy.py
- mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
- mobsf/DynamicAnalyzer/views/android/environment.py
- mobsf/MobSF/init.py
- mobsf/templates/dynamic_analysis/dynamic_analysis.html
```
* Support Android Dynamic Analysis with Docker
* Added support for Android 11, API 30 from Genymotion
* Android Dynamic Analyzer bug fixes
* CA cert install
* Package listing error
* Dockerfile Bug fixes
* Pin pip to fix broken tests
```
```
DESCRIBE HERE
```
> HOTFIX: MobSF Android Dynamic Analysis Docker Support

- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
```
Update APktool to the last version
- feat: Upgrade gradle to v8.2.1 by @ArjunaKumarMohanta in https://github.com/iBotPeaches/Apktool/pull/3141
- build(deps): bump gradle/gradle-build-action from 2.5.1 to 2.6.0 by https://github.com/dependabot in https://github.com/iBotPeaches/Apktool/pull/3151
- fix: skip files if cleaned to empty filename by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/3166
- fix: opt out of stricter java rules for zip64 and dot entries by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/3178
- build: test on java20 by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/3177
- Correct regressions towards apktool.yml generation by @iBotPeaches in https://github.com/iBotPeaches/Apktool/pull/3172
- Allows run app from gradle for …
```
> update apktool to 2.8.1

- mobsf/DynamicAnalyzer/views/android/dynamic_analyzer.py
- mobsf/templates/dynamic_analysis/dynamic_analysis.html
```
Dynamic Analyzer Support Alert 
```
```
DESCRIBE HERE
```
> HOTFIX: Dynamic Analyzer Support Alert

- mobsf/MobSF/init.py
- mobsf/MobSF/utils.py
- mobsf/StaticAnalyzer/views/android/rules/android_niap.yaml
- mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
- mobsf/StaticAnalyzer/views/ios/rules/ios_apis.yaml
- mobsf/StaticAnalyzer/views/ios/rules/objective_c_rules.yaml
- mobsf/StaticAnalyzer/views/ios/rules/swift_rules.yaml
- mobsf/install/windows/setup.py
- mobsf/templates/general/home.html
```
* IOS Swift Rules updates
*  Updated or added rules `ios_biometric_bool`, `ios_biometric_acl`, `ios_keychain_weak_acl_device_passcode`, `ios_keychain_weak_accessibility_value`, `ios_insecure_random_no_generator`, `ios_biometry_hardened`
* Regex Hardening: Fixes possible Regex DoS in rules and MobSF code base
```
```
DESCRIBE HERE
```
> [HOTFIX] Regex + Rule Update

- mobsf/StaticAnalyzer/views/android/binary_analysis.py
- mobsf/StaticAnalyzer/views/android/jar_aar.py
- mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml
- mobsf/StaticAnalyzer/views/ios/macho_analysis.py
- mobsf/templates/pdf/android_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
```
* AAR/JAR obfuscation via `LocalVariableTable`
* Added an Android SAST rule to  detect AAR/JAR with debug enabled.
* Exception handling for LIEF ELF/MachO strings and symbols extraction
```
```
DESCRIBE HERE
```
> [EFR09] AAR/JAR obfuscation and debug check + Exception Handed strings and symbols extraction

- .github/workflows/docker-test.yml
```
Test to ensure that docker images can be built for amd64 and arm64
```
```
DESCRIBE HERE
```
> Docker Buildx test

- mobsf/MobSF/views/api/api_static_analysis.py
- mobsf/StaticAnalyzer/tests.py
- mobsf/templates/general/apidocs.html
```
* Simplify Scan API
* Need only scan hash to trigger a scan
```
```
DESCRIBE HERE
```
> Simplify Scan API

- mobsf/MobSF/settings.py
- mobsf/StaticAnalyzer/views/android/icon_analysis.py
```
Support WebP icons
```
```
DESCRIBE HERE
```
> [HOTFIX] Support webp for icon

- mobsf/StaticAnalyzer/views/android/icon_analysis.py
fixed that the icon cannot be found when the suffix name is uppercase
> fixed that the icon cannot be found

- mobsf/MobSF/settings.py
```
Allow jpeg icons for android.
```
```
DESCRIBE HERE
```
> [HOTFIX] Allow jpeg icons

- mobsf/MobSF/init.py
- mobsf/StaticAnalyzer/views/android/jar_aar.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- mobsf/StaticAnalyzer/views/android/manifest_utils.py
- mobsf/StaticAnalyzer/views/common/binary/elf.py
- mobsf/StaticAnalyzer/views/common/binary/macho.py
- mobsf/StaticAnalyzer/views/common/binary/strings.py
- mobsf/StaticAnalyzer/views/common/shared_func.py
- mobsf/StaticAnalyzer/views/ios/binary_analysis.py
- mobsf/StaticAnalyzer/views/ios/strings.py
- mobsf/templates/pdf/android_report.html
- mobsf/templates/static_analysis/android_binary_analysis.html
- poetry.lock
```
* P1.1 AAR Permissions not properly listed 
* P1.2 Local variable table not listed in proper section
* P1.3 static library strings are not listed
* P1.5 Stripping of dynamic and static libraries are not correctly reported
* Dependency bump
* MobSF version bump
```
```
DESCRIBE HERE
```
> [HOTFIX][EFR] Priority Bug Fixes

- mobsf/StaticAnalyzer/views/android/manifest_utils.py
```
Upgrade APktool to 2.9.0
https://github.com/iBotPeaches/Apktool/releases/tag/v2.9.0
```
> update apktool to 2.9.0

- mobsf/MobSF/init.py
- mobsf/templates/dynamic_analysis/ios/dynamic_analyzer.html
- mobsf/templates/general/apidocs.html
- pyproject.toml
```
REST API Docs Update for Frida Instrument
```
```
DESCRIBE HERE
```
> Dec 2023 QA

- mobsf/StaticAnalyzer/views/android/manifest_utils.py
```
Upgrade Apktool to 2.9.1
https://github.com/iBotPeaches/Apktool/releases/tag/v2.9.1
```
> update apktool to 2.9.1

- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
[ERROR] 2024-01-10 10:28:29 - Well Known Assetlinks Check for URL: http://*/.well-known/assetlinks.json Traceback (most recent call last):
requests.exceptions.InvalidURL: URL has an invalid label.
```
```
```
DESCRIBE HERE
```
> Filter out invalid links

- mobsf/StaticAnalyzer/views/android/cert_analysis.py
- poetry.lock
- pyproject.toml
> poetry pyqt5 fixes

- mobsf/MobSF/init.py
- mobsf/MobSF/security.py
- mobsf/MobSF/settings.py
- mobsf/MobSF/views/api/api_static_analysis.py
- mobsf/MobSF/views/helpers.py
- mobsf/MobSF/views/home.py
- mobsf/MobSF/views/scanning.py
- mobsf/StaticAnalyzer/tests.py
- mobsf/StaticAnalyzer/views/android/static_analyzer.py
- mobsf/StaticAnalyzer/views/android/xapk.py
- mobsf/StaticAnalyzer/views/common/shared_func.py
- mobsf/StaticAnalyzer/views/ios/static_analyzer.py
- mobsf/StaticAnalyzer/views/windows/windows.py
- mobsf/templates/general/home.html
- mobsf/templates/general/recent.html
- pyproject.toml
* Fixes #2387
* Convert AAB -> APKS -> APK
* Add bundletool for AAB conversion
```
DESCRIBE HERE
```
> [HOTFIX] Support AAB with MobSF, Convert AAB to APK, Fixes #2387

- Dockerfile
- mobsf/DynamicAnalyzer/tools/frida_scripts/android/default/debugger_check_bypass.js
- mobsf/DynamicAnalyzer/tools/frida_scripts/android/default/root_bypass.js
- mobsf/MobSF/init.py
- mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml
- mobsf/StaticAnalyzer/views/common/shared_func.py
- poetry.lock
- pyproject.toml
- scripts/entrypoint.sh
```
* Dockerfile QA
* Prevent docker container exits on volume mount
* Android Frida root bypass and debugger bypass scripts improvements
* Android SAST Rule `setAllow*FromFileURLs`
* Dependency Updates
```
```
DESCRIBE HERE
```
> [HOTFIX] Code QA

- .github/SECURITY.md
> [HOTFIX] SECURITY.md

- poetry.lock
> [HOTFIX] Bump deps

- mobsf/MobSF/urls.py
- poetry.lock
```
Dep bump oct 2024
Fixes #2424 
```
```
DESCRIBE HERE
```
> [HOTFIX] dep bups + Fix #2424

- mobsf/MobSF/init.py
- poetry.lock
- pyproject.toml
```
Major performance update, address #2162
```
```
DESCRIBE HERE
```
> Libsast bump

- docker/docker-compose.yml
- docker/docker-compose_swarm.yml
- docker/nginx.conf
- mobsf/DynamicAnalyzer/tools/apk_patcher.py
- mobsf/DynamicAnalyzer/tools/webproxy.py
- mobsf/DynamicAnalyzer/views/android/frida_server_download.py
- mobsf/DynamicAnalyzer/views/ios/corellium_apis.py
- mobsf/MalwareAnalyzer/views/VirusTotal.py
- mobsf/MobSF/init.py
- mobsf/MobSF/settings.py
- mobsf/MobSF/tools_download.py
- mobsf/MobSF/views/apk_downloader.py
- mobsf/StaticAnalyzer/views/android/manifest_analysis.py
- mobsf/StaticAnalyzer/views/android/playstore.py
- mobsf/StaticAnalyzer/views/common/firebase.py
- mobsf/StaticAnalyzer/views/ios/appstore.py
- poetry.lock
- pyproject.toml
- scripts/update_android_permissions.py
```
* Dependency update
* Explicit timeout for all requests
* Support proxy for all http(s) calls
* Optimize jadx download, support system proxy
```
```
DESCRIBE HERE
```
> docker compose QA, explict requests timeout

- mobsf/StaticAnalyzer/views/common/async_task.py
```
[4.2.3] Update status on task timeout
```
```
DESCRIBE HERE
```
> [4.2.3] Update status on task timeout

- poetry.lock
- pyproject.toml
> Byte snipers patch 2

- .github/workflows/supply_chain.yml
```
Add Socket Supply Chain Firewall job
```
```
DESCRIBE HERE
```
> Socket Supply Chain Scan
